### ISSUE TITLE
Create basic 16S pipeline

### ISSUE THREAD

**Issue by rmcminds** [McMinds-Lab/analysis_templates#1]
Within /microbiomes, upload a script with basic 16S data processing using DADA2, from raw sequence data to an OTU table

**Comment by santiagohern25** [comment]
Hello Dr. McMinds! I added the 16S Pipeline. Thank you!

Santiago

**Comment by rmcminds** [comment]
great! I see you created separate branches in your forked repository - I made a pull request to merge your other script into this repository; why don't you do it yourself for this one so we can test out that system? And I'll keep this issue open while I look over the code and see if there are any edits to talk about
